print("Enter your name:")
name = input("Enter your name:")
print("Hello" , name , "Welcome to the world of coding")
print("Enter your age:")
age = input("Enter your age:")
age = int(age)
print("Your age is" , age)
print("Enter your weight:")
weight = input("Enter your weight:")
weight = int(weight)
print("Your weight is:" , weight)